# Real-Time Speaker Isolation & Identification Configuration

# Audio Configuration
audio:
  sample_rate: 16000
  chunk_duration: 1.0  # seconds
  buffer_size: 4096
  device_index: null  # null for default microphone
  
# Model Configuration
models:
  # Speech Separation
  separation:
    model_name: "sepformer-wham"
    device: "cuda"  # "cuda" or "cpu"
    batch_size: 1
    
  # Speaker Recognition
  speaker_recognition:
    model_name: "speechbrain/spkrec-ecapa-voxceleb"
    device: "cuda"  # "cuda" or "cpu"
    embedding_dim: 192
    similarity_threshold: 0.7
    
  # Speech Recognition
  transcription:
    model_name: "whisper"
    model_size: "tiny"  # "tiny", "base", "small", "medium", "large"
    device: "cuda"  # "cuda" or "cpu"
    language: "en"
    
# Processing Configuration
processing:
  max_speakers: 4
  min_speaker_duration: 0.5  # minimum duration to consider a speaker
  overlap_threshold: 0.3  # threshold for speaker overlap detection
  confidence_threshold: 0.5  # minimum confidence for speaker identification
  
# Storage Configuration
storage:
  speaker_embeddings_dir: "./data/speaker_embeddings"
  audio_cache_dir: "./data/audio_cache"
  transcripts_dir: "./data/transcripts"
  
# Server Configuration
server:
  host: "localhost"
  port: 8000
  websocket_port: 8001
  
# UI Configuration
ui:
  update_interval: 0.5  # seconds between UI updates
  max_transcript_length: 1000  # maximum characters in transcript display
  waveform_points: 200  # number of points for waveform visualization
